### ISSUE TITLE
spotify-player.herokuapp.com is down.

### ISSUE THREAD

**Issue by oftaict** [JMPerez/spotify-player#2]
Hi,

The spotify-player.herokuapp.com application is down.
Is this temporary?

Thanks in advance for your reply.

**Comment by JMPerez** [comment]
It looks like my usage of Heroku exceeded the free limit. If you are using this library for your own application I would recommend you to set it up with your own credentials to ensure availability. Follow the instructions on https://github.com/JMPerez/spotify-player#server

**Comment by JMPerez** [comment]
Fixed now
