### ISSUE TITLE
Can´t login

### ISSUE THREAD

**Issue by tiito78** [JMPerez/spotify-player#3]
Hola José!

muchas gracias por este script tan bueno. Hermano tengo un problema y es que no se puede iniciar. Lo que puedo ver es el sigiente error: 

`Logging user out due to error SyntaxError: Unexpected end of JSON input
    at fetchGeneric.then.response (spotify-player.js:161)
    at <anonymous>`

Otra vez, muchas gracias por tu trabajo tan bueno. Y espero que me puedas guiar a una solucion.

**Comment by JMPerez** [comment]
@tiito78 ¿Podrías ver qué respuesta estás obteniendo del endpoint de Spotify? Puede que sea un error puntual en el servicio de Spotify, y no parece que sea un problema de la librería.

**Comment by tiito78** [comment]
Parece que el error era de Spotify, porque ya me funciona. Muchas gracias por tu tiempo!

**Comment by JMPerez** [comment]
👍🏼
